export const API={
    // API_BASEURL:'https://bookexchange-backend-1.onrender.com',
    API_BASEURL:'http://192.168.90.222:4002',
    // API_BASEURL:'http://192.168.209.222:4002',
    HOSETL_REGISTRATION:'auth/register_hostel',
    REGISTER:'auth/register',
    LOGIN:'bookApp/login',
    GET_MY_PROFILE:'bookApp/user',
    GET_ALL_BOOKS:'bookApp/getBooks',
    GET_LATEST_BOOKS:'bookApp/get_new_books_hostelwise',
    ADD_BOOK:'add_book',
    GET_BOOKS_CATEGORYWISE:'bookApp/get_books_categorywise',
    GET_BY_HOSTEL_CATEGORY:'bookApp/get_books_category_hostel',
    GET_BOOKS_HOSTELWISE:'bookApp/get_books_hostelwise',
    HOSTELWISE_USER:'bookApp/users_hostelwise',
    USER_DETAILS:'bookApp/specific_user',
    HOSTEL_LIST:'get_all_hostels',
    GET_PRODUCT_DETAIL:'bookApp/getBookDetail',
    GET_USER_BOOKS:'bookApp/get_my_products',
    DELETE_BOOK:'bookApp/delete_product',
    GET_HOSTELS:'get_hostels'
}